spring:
  application:
    name: admin-service
  datasource:
    url: jdbc:mysql://bd-ferramas-admin.crwi4crvnqsy.us-east-1.rds.amazonaws.com
    username: Ferremas_adm
    password: C.AdmFerremas
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect

server:
  port: 3306
